name: realtime_image_labeler
description: "A Flutter widget for real-time object detection using the camera and SSD MobileNet."
version: 0.1.0
homepage: https://github.com/Estudio-Tarzia/realtime_image_labeler
repository: https://github.com/Estudio-Tarzia/realtime_image_labeler
license: MIT


environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: 0.11.0
  exif: 3.1.4
  camera: ^0.11.1
  camera_android: ^0.10.10
  image: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter: 
  assets:
    - assets/
    
      